version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"  # Path to pubspec.yaml
    schedule:
      interval: "weekly"  # Check for updates every week
    allow:
      - dependency-type: "direct"  # Only update direct dependencies
    ignore:
      - dependency-name: "flutter"  # Ignore Flutter SDK updates
    open-pull-requests-limit: 10
    rebase-strategy: auto
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
    reviewers:
      - "Devofure"
    assignees:
      - "Devofure"