name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter Analyze
      - name: Run flutter analyze
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
